-- Harden account-owned record storage and retain a bounded server-side history.

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_records_records_object_check'
      and conrelid = 'public.user_records'::regclass
  ) then
    alter table public.user_records
      add constraint user_records_records_object_check
      check (jsonb_typeof(records) = 'object');
  end if;
end $$;

create table if not exists public.user_record_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  records jsonb not null,
  source_updated_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint user_record_backups_records_object_check
    check (jsonb_typeof(records) = 'object')
);

create index if not exists user_record_backups_user_created_idx
  on public.user_record_backups (user_id, created_at desc);

alter table public.user_record_backups enable row level security;

revoke all on table public.user_record_backups from anon;
revoke insert, update on table public.user_record_backups from authenticated;
grant select, delete on table public.user_record_backups to authenticated;

drop policy if exists "Users view only their own record backups"
  on public.user_record_backups;
create policy "Users view only their own record backups"
on public.user_record_backups
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users delete only their own record backups"
  on public.user_record_backups;
create policy "Users delete only their own record backups"
on public.user_record_backups
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.archive_user_record_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and old.records is not distinct from new.records then
    return new;
  end if;

  insert into public.user_record_backups (
    user_id,
    records,
    source_updated_at
  ) values (
    old.user_id,
    old.records,
    old.updated_at
  );

  delete from public.user_record_backups
  where user_id = old.user_id
    and id not in (
      select id
      from public.user_record_backups
      where user_id = old.user_id
      order by created_at desc, id desc
      limit 30
    );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists archive_user_record_snapshot
  on public.user_records;
create trigger archive_user_record_snapshot
before update or delete on public.user_records
for each row execute function public.archive_user_record_snapshot();

create or replace function public.touch_user_record_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_user_record_updated_at
  on public.user_records;
create trigger touch_user_record_updated_at
before insert or update on public.user_records
for each row execute function public.touch_user_record_updated_at();
