create table if not exists public.user_records (
  user_id uuid primary key references auth.users(id) on delete cascade,
  records jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_records enable row level security;

drop policy if exists "Users manage only their own records" on public.user_records;
create policy "Users manage only their own records"
on public.user_records
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_records_records_object_check'
      and conrelid = 'public.user_records'::regclass
  ) then
    alter table public.user_records
      add constraint user_records_records_object_check
      check (jsonb_typeof(records) = 'object');
  end if;
end $$;

-- Keep the latest 30 pre-change snapshots per account. Only the owning user
-- can read or delete snapshots; inserts happen exclusively through the trigger.
create table if not exists public.user_record_backups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  records jsonb not null,
  source_updated_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint user_record_backups_records_object_check
    check (jsonb_typeof(records) = 'object')
);

create index if not exists user_record_backups_user_created_idx
on public.user_record_backups (user_id, created_at desc);

alter table public.user_record_backups enable row level security;

revoke all on table public.user_record_backups from anon;
revoke insert, update on table public.user_record_backups from authenticated;
grant select, delete on table public.user_record_backups to authenticated;

drop policy if exists "Users view only their own record backups" on public.user_record_backups;
create policy "Users view only their own record backups"
on public.user_record_backups
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users delete only their own record backups" on public.user_record_backups;
create policy "Users delete only their own record backups"
on public.user_record_backups
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.archive_user_record_snapshot()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and old.records is not distinct from new.records then
    return new;
  end if;

  insert into public.user_record_backups (user_id, records, source_updated_at)
  values (old.user_id, old.records, old.updated_at);

  delete from public.user_record_backups
  where user_id = old.user_id
    and id not in (
      select id
      from public.user_record_backups
      where user_id = old.user_id
      order by created_at desc, id desc
      limit 30
    );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists archive_user_record_snapshot on public.user_records;
create trigger archive_user_record_snapshot
before update or delete on public.user_records
for each row execute function public.archive_user_record_snapshot();

create or replace function public.touch_user_record_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_user_record_updated_at on public.user_records;
create trigger touch_user_record_updated_at
before insert or update on public.user_records
for each row execute function public.touch_user_record_updated_at();

-- A short-lived code links one Feishu identity to one Daily Space account.
create table if not exists public.feishu_binding_codes (
  code text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists feishu_binding_codes_user_id_idx
on public.feishu_binding_codes (user_id);

create table if not exists public.feishu_bindings (
  open_id text primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.feishu_processed_messages (
  message_id text primary key,
  processed_at timestamptz not null default now()
);

alter table public.feishu_binding_codes enable row level security;
alter table public.feishu_bindings enable row level security;
alter table public.feishu_processed_messages enable row level security;

drop policy if exists "Users view their own Feishu binding codes" on public.feishu_binding_codes;
create policy "Users view their own Feishu binding codes"
on public.feishu_binding_codes
for select
to authenticated
using (auth.uid() = user_id);

-- Imported images are uploaded only by the server using the service role.
insert into storage.buckets (id, name, public)
values ('feishu-imports', 'feishu-imports', false)
on conflict (id) do update set public = false;
