"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpen, CheckCircle2, Flame, StickyNote } from "lucide-react";
import { listJournals, todayKey } from "@/lib/journals";
import { listNotes } from "@/lib/notes";

type Plan = { tasks?: Array<{ done: boolean }> };
type Stats = { journalCount: number; streak: number; noteCount: number; taskDone: number; taskTotal: number };
function getStats(): Stats { const journals = listJournals(); const dates = new Set(journals.map((entry) => entry.date)); let streak = 0; const cursor = new Date(`${todayKey()}T12:00:00`); while (dates.has([cursor.getFullYear(), String(cursor.getMonth() + 1).padStart(2, "0"), String(cursor.getDate()).padStart(2, "0")].join("-"))) { streak += 1; cursor.setDate(cursor.getDate() - 1); } let tasks: Array<{ done: boolean }> = []; try { tasks = (JSON.parse(window.localStorage.getItem(`daily-space:plan:${todayKey()}`) ?? "{}") as Plan).tasks ?? []; } catch { /* Ignore invalid local plan data. */ } return { journalCount: journals.length, streak, noteCount: listNotes().length, taskDone: tasks.filter((task) => task.done).length, taskTotal: tasks.length }; }

export function DashboardInsights() { const [stats, setStats] = useState<Stats>({ journalCount: 0, streak: 0, noteCount: 0, taskDone: 0, taskTotal: 0 }); useEffect(() => { const refresh = () => setStats(getStats()); refresh(); const events = ["daily-space:journals-changed", "daily-space:notes-changed", "daily-space:plans-changed"]; events.forEach((event) => window.addEventListener(event, refresh)); return () => events.forEach((event) => window.removeEventListener(event, refresh)); }, []); const cards = [{ href: "/plan", icon: CheckCircle2, value: stats.taskTotal ? `${stats.taskDone}/${stats.taskTotal}` : "-", label: "今日待办完成", tone: "bg-[#edf6ef] text-[#35704b]" }, { href: "/journals", icon: Flame, value: stats.streak, label: "连续记录天数", tone: "bg-[#fff3e5] text-[#a5632e]" }, { href: "/journals", icon: BookOpen, value: stats.journalCount, label: "已写日记", tone: "bg-[#eef2fb] text-[#526b9b]" }, { href: "/notes", icon: StickyNote, value: stats.noteCount, label: "随记条目", tone: "bg-[#f9eff3] text-[#9b5d75]" }]; return <section className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ href, icon: Icon, value, label, tone }) => <Link key={label} href={href} className="group rounded-xl border border-[#dce6de] bg-white px-4 py-4 shadow-[0_1px_2px_rgba(31,67,45,0.03)] hover:-translate-y-0.5 hover:border-[#a6c2ae] hover:shadow-[0_8px_20px_rgba(35,75,51,0.08)]"><span className={`grid h-8 w-8 place-items-center rounded-lg ${tone}`}><Icon size={16} strokeWidth={1.8} /></span><div className="mt-4 flex items-end justify-between gap-2"><div><strong className="block text-2xl font-semibold tracking-normal text-[#203126]">{value}</strong><span className="mt-1 block text-sm text-[#718077]">{label}</span></div><span className="text-xs text-[#93a197] opacity-0 transition-opacity group-hover:opacity-100">查看</span></div></Link>)}</section>; }
