"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Check, CircleDotDashed } from "lucide-react";
import { habitStreak, listHabits, toggleHabit, type Habit } from "@/lib/habits";
import { todayKey } from "@/lib/journals";

export function HabitProgress() { const [habits, setHabits] = useState<Habit[]>([]); useEffect(() => { const refresh = () => setHabits(listHabits()); refresh(); window.addEventListener("daily-space:habits-changed", refresh); return () => window.removeEventListener("daily-space:habits-changed", refresh); }, []); const today = todayKey(); if (!habits.length) return null; return <section className="mt-6 rounded-xl border border-[#d9e2da] bg-white p-5 md:p-6"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-[#2f6651]"><CircleDotDashed size={18} strokeWidth={1.8} /><h2 className="font-semibold">今日习惯</h2></div><p className="mt-1 text-sm text-[#718077]">每一次打卡都会更新你的坚持记录，没有天数上限。</p></div><Link href="/goals#habits" className="text-sm font-medium text-[#2f6651] hover:text-[#245440]">管理习惯</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{habits.map((habit) => { const checked = habit.completedDates.includes(today); const streak = habitStreak(habit); const total = habit.completedDates.length; return <article key={habit.id} className="flex items-center gap-4 rounded-lg border border-[#e1e8e2] p-4"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-full border-4 border-[#2f6651] bg-[#edf5ef] text-center"><strong className="text-base leading-4">{streak}</strong><span className="text-[10px] text-[#718077]">连续天</span></div><div className="min-w-0 flex-1"><h3 className="truncate font-medium">{habit.name}</h3><p className="mt-1 text-xs text-[#718077]">累计打卡 {total} 天</p><button onClick={() => { toggleHabit(habit.id); setHabits(listHabits()); }} className={`mt-3 inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs font-medium ${checked ? "border-[#a9c5b6] bg-[#edf5ef] text-[#2f6651]" : "border-[#cfd8d0] text-[#526158] hover:bg-[#f5f8f5]"}`}>{checked ? <Check size={14} strokeWidth={1.8} /> : null}{checked ? "今日已打卡" : "今日打卡"}</button></div></article>; })}</div></section>; }
